version: '3.1'

services:

  wordpress:
    build:
      context: ..
      dockerfile: docker/wp/Dockerfile
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: testpass
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_CONFIG_EXTRA:
        define( 'WP_DEBUG', true );
        define( 'FS_METHOD', 'direct' );
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
      - 33061:33061
      - 33062:33062
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  
  cli:
    build:
      context: ..
      dockerfile: docker/wp-cli/Dockerfile
    depends_on:
      - wordpress
      - db
    environment:
      WP_CLI_CONFIG_PATH: /wp-cli.yml
      WPCORE_URL: http://localhost:8080
      WPCORE_TITLE: Nosnitor theme demo
      WPCORE_ADMINUSER: admin
      WPCORE_ADMINPASS: pass
      WPCORE_ADMINEMAIL: wp-admin@phloxis.com
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db: